---
title: Problem Set 3
number-sections: true
engine: julia
---

## Accretion onto Black Holes

### Minimum wavelength

```{julia}
using DrWatson
include(srcdir("astr145/main.jl"))
```

```{julia}
using Unitful, UnitfulAstro
using Unitful: mp, G, c, σ
using UnitfulAstro: Msun, Rsun, AU

b = 2.8977729e-3u"m*K"
# Wien displacement law
λ_max(T) =  b / T |> upreferred
T(M, R) = (G * M * L_edd(M) / (8π * σ * R^3 * c^2))^(1/4) |> upreferred
R_in_nonrot(M) = 6 * G * M / c^2 
R_in_rot(M) = G * M / c^2

let M = 1e8u"Msun"
    t = T(M, R_in_nonrot(M))
    λmax = λ_max(t) |> upreferred
    @show t
    @show λmax
    @show uconvert(u"nm", λmax)
end

let M = 30u"Msun"
    t = T(M, R_in_rot(M))
    λmax = λ_max(t)
    @show t
    @show λmax
    @show uconvert(u"nm", λmax)
end;
```

## Stellar Tidal Disruption

```{julia}
d = (4.1e6)^(1/3) * Rsun
@show d
@show d/AU |> NoUnits
@show Rsch(4.1e6u"Msun");
```

## Black Holes Through Time

> In the nearby Universe, black holes seem  to be ubiquitous in galaxies: to a reasonable approximation, every galaxy has a central  supermassive black hole with a mass about one four-thousandth of its stellar mass. Assuming all these black holes grew through disk accretion, compare (quantitatively  though approximately!) the total energy of radiation they have generated to the total  energy generated by stars. You will need to make some assumptions along the way;  please be clear about them!

Assume:

- Accretion Efficiency $\eta$ is about 10% .
- Stellar Fusion Efficiency $\eta_f$ is about 0.7% .

$$
E_{\text{BH}} = \eta \times M_{\text{BH}} \times c^2 = \eta \times \left( \frac{M_*}{4000} \right) \times c^2
$$

Energy generated by stars through nuclear fusion:

$$
E_* = \eta_f \times M_* \times c^2
$$

So

$$
\frac{E_{\text{BH}}}{E_*} = \frac{\eta \left( \frac{M_*}{4000} \right)  c^2}{\eta_f M_* c^2} = \frac{\eta}{4000 \eta_f} \approx 0.0036
$$

## The Magnetorotational Instability

Accretion disks typically exhibit differential rotation. So as the disk rotates, fluid elements become more azimuthally separated. Magnetic tension oppose such separation, however, such force acts to decrease the angular momentum of the inner fluid element and increase that of the outer element. Because angular momentum is an increasing function of radius in Keplerian disks, this transfer of angular momentum causes the fluid elements to separate further radially, leading to instability. This continuously growing stretching and twisting of magnetic field lines generate MHD turbulence. The turbulent motions effectively act as a efficient “viscous” force, facilitating the transfer of angular momentum.