---
title: Problem Set 6
number-sections: true
engine: julia
---

## Synchrotron Cooling

### Half-time for Energy Loss

> Show that the time for an electron to lose half its energy is

```{julia}
using DrWatson
using Unitful: Mass, Length
include(srcdir("astr145/main.jl"))
```

```{julia}
using Unitful: c, q, me, μ0, ϵ0

B_con = sqrt(4π / μ0)
q_factor = 1 / sqrt(4π * ϵ0)

t_half(B, γ0; m=me) = (3 * m^3 * c^5) / (2 * (q_factor * q)^4 * (B * B_con)^2 * γ0) |> upreferred
t_half(10u"μGauss", 1e6)
```


## Compact Objects

> White dwarfs, neutron stars, and stellar-mass black holes are all compact objects formed at the final stages of stellar evolution. Here, you  will compare some of their fundamental properties. Assume typical white dwarfs have M ≈ M_sun and a radius comparable to Earth. For neutron stars, assume M ≈ 2 M_sun and a radius of 10 km.

### Escape Velocities

> Estimate the escape velocity at the surfaces of white dwarfs and neutron stars, and compare them to that of a black hole.

```{julia}
using UnitfulAstro: Msun, Rearth

M_white_dwarf = 1u"Msun"
M_neutron_star = 2u"Msun"
M_black_hole = 10u"Msun"

R_white_dwarf = Rearth
R_neutron_star = 10u"km"

v_es_white_dwarf = let M = M_white_dwarf, R = R_white_dwarf
    @show v_es(M, R)
end

v_es_neutron_star = let M = M_neutron_star, R = R_neutron_star
    @show v_es(M, R)
end

v_es_black_hole = let M = M_black_hole
    R = Rsch(M)
    @show v_es(M, R)
end

println("White dwarf to black hole: ", v_es_white_dwarf / v_es_black_hole)
println("Neutron star to black hole: ", v_es_neutron_star / v_es_black_hole)
```

Neutron stars have the comparable escape velocity to black holes, while white dwarfs have a much lower escape velocity (1% of the black hole's).

### Gravitational Acceleration

> Estimate the gravitational acceleration at the surface of a white dwarf and neutron  star, and compare them with that at the Schwarzschild radius of a black hole with  M ≈ 10 M . Would humans be able to survive this gravity?

```{julia}
g(M, R) = G * M / R^2 |> upreferred

g0 = 9.8u"m/s^2"

g_white_dwarf = let M = 1u"Msun", R = Rearth
    @show g(M, R)
end

g_neutron_star = let M = 2u"Msun", R = 10u"km"
    @show g(M, R)
end

g_black_hole = let M = 10u"Msun"
    R = Rsch(M)
    @show g(M, R)
end

NoUnits(minimum([g_white_dwarf, g_neutron_star, g_black_hole]) / g0)
```

Humans would not be able to survive the gravity of white dwarfs or neutron stars or black holes.


### Gravitational Redshift

> Recall that near a massive object, light experiences a gravitational redshift:

```{julia}
z(M, R) = sqrt(1 - 2 * G * M / (R * c^2))

@show z(M_white_dwarf, R_white_dwarf)
@show z(M_neutron_star, R_neutron_star)
@show z(M_black_hole, R_ISCO(M_black_hole))
```

## Ultra-High Energy Cosmic Rays

> Read this article about ultra-high  energy cosmic rays: https://physicsworld.com/a/the-riddle-of-ultrahigh-energy-cosmic-rays/  Write a short reaction (a paragraph or so) to this video – you could comment on  something you learned or particularly enjoyed or pose a question it raised to you, for example.

I was particularly intrigued by the challenges in identifying the sources of UHECRs due to their deflection by magnetic fields, which obscures their paths. This raises a compelling question: how can we develop methods or technologies to trace these particles back to their origins, thereby unveiling the astrophysical processes responsible for such extreme energies?