project:
  type: website
  preview: 
    port: 5555

execute:
  freeze: auto

bibliography: files/references.bib

website:
  title: "beforerr"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    tools:
      - icon: github
        href: "https://github.com/Beforerr/beforerr"
  sidebar:
    contents: auto
  page-navigation: true
  repo-url: "https://github.com/Beforerr/beforerr"
  repo-actions: [source, issue]

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-fold: true
    # code-tools: true
