project:
  type: website
  preview: 
    port: 5555

bibliography:
  - files/references.bib
  - ../share/bibliography/research.bib


website:
  title: "beforerr"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - docs/research/index.qmd
      - text: "Others"
        menu: 
          - href: docs/blog/index.qmd
          - href: docs/courses/index.qmd
          - href: docs/projects/index.qmd
    tools:
      - icon: github
        href: "https://github.com/Beforerr/beforerr"
  sidebar:
    - contents: docs/courses
      id: courses
    - contents: docs/projects
      id: projects
  page-footer:
    center:
      - text: "About"
        href: about.qmd
  page-navigation: true
  bread-crumbs: true
  repo-url: "https://github.com/Beforerr/beforerr"
  repo-actions: [source, issue]

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true

wrap: preserve