[project]
name = "beforerr"
version = "0.1.0"
description = "Add a short description here"
authors = ["Beforerr <zzj956959688@gmail.com>"]
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[tasks]

[dependencies]
jupyter = "*"
