## On the origin of solar wind current sheets

- @matthaeusIntermittencyNonlinearDynamics2015

interplanetary field is composed of a large number of separate filamentary tubes that originate at the sun.

Many such discontinuities are visible on mesoscales (~4 days, ~1 AU). Earlier interpretations had proposed that discontinuities are simply boundaries of spaghetti-like filaments extending from the Sun to the Earth, but @burlagaDirectionalDiscontinuitiesInterplanetary1969 showed that well-ordered filaments with sharp boundaries are not always present even though discontinuities are ubiquitous. This observation favors a _discontinuous_ rather than _filamentary_ model of the interplanetary medium, allowing for the possibility that discontinuities form in situ far from the Sun rather than being exclusively convected from the corona.

- @neugebauerCommentAbundancesRotational2006
  - Abstract: "Neugebauer and Buti [1990] failed to find the plasma and field signatures predicted for the evolution of Alfve ́n waves into solitons and thence into RDs."
  - "A final possibility is that the distinction between RDs and TDs is an oversimplification of reality. Along that line, De Keyser et al. [1998, p. 2652] suggest that ‘‘most solar wind TDs, at least in the fast wind, are a particular case of RDs, that is, phase-steepened large-amplitude Alfve ́n waves [Tsurutani et al., 1994] that happen to propagate quite slowly as their wave vector is nearly perpendicular to the magnetic field.’’"
- @vasquezNumerousSmallMagnetic2007
  - """Association With Discontinuities From Flux Tubes
    The tangential discontinuity is a boundary with a normal across the background magnetic field. The TD can support waves but here its formation is limited to a discontinuity which is not the result of Alfve ́n wave evolution or Alfve ́nic turbulence. Instead, we consider cases where the magnetic field develops thin current sheets in association with flux tube dynamics at the Sun. [56] At the photosphere, the magnetic field is strongest in small magnetic bright points [e.g., G-band bright points] between granules in the network which lie along the boundary of supergranules. These bright points have scales of 100 to 200 km in the photosphere and average separations of 350 to 700 km. Cranmer and van Ballegooijen [2005] developed a model of an open-field source region using these bright points which we use here to describe flux tube structure. From these bright points, the magnetic field is constrained on the outside mostly by plasma pressure and is vertical. In the low chromosphere at an altitude of about 2000 km, the lower gas pressure causes the flux tubes to expand until they form boundaries adjacent to one another. Current sheets could characterize all of these boundaries and possibly yield a flux tube structure that could be found in the solar wind. Because collisions are so infrequent, the current sheets can have thicknesses which are as small as the proton inertial length and so correspond to TDs in the solar wind. A possible constraint on whether or not the discontinuities are rooted in the Sun comes from the rapid Figure 13. Histogram of widths based on normal direction in units of (a) proton inertial length c/wpp and (b) proton gyroradius rgp for 203 discontinuities where plasma proton b is less than 0.1. In these plasma conditions, c/wpp is larger than rgp. Part (a) has a similar distribution of widths as is seen in Figure 12a, while in part (b) widths are larger in gyroradii and have not thinned proportionally to rgp. This indicates that c/wpp determines the widths for small b. For large b > 4 (not shown) results are consistent with widths determined by rgp. time-scale of evolution for the solar magnetic field. The magnetic field at the Sun undergoes reconnection on a scale of 1.4 h [e.g., Close et al., 2004]. If the reconnection is an interchange between closed and open field lines, then current sheets may be continuously rooted in the Sun if the result is a braiding of magnetic fields emanating from separate bright points. [57] A number of properties of the observed discontinuities are consistent with TDs. Within measurement uncertainty discontinuities with triangulated normals can have zero normal field components which are consistent with TDs [e.g., Knetter et al., 2004]. The magnetic field intensity and direction typically change across the layer of all discontinuities. TDs are unlimited in these changes and generally such changes would be expected to be observed among a large number of TDs. The lognormal distribution of separations between discontinuities could be due to net fragmentation of magnetic field flux concentrations from advection and reconnection at the Sun. [58] However, there are far more identified discontinuities than expected of solar wind flux tubes. Near 1 AU, z et al. [1966] and McCracken and Ness [1966] inferred that energetic ions follow magnetic field lines with abrupt changes in direction (within the 7.5 min resolution of particle sampling) occurring about every 0.5– 4 h or 0.54 106 km. They interpreted the abrupt changes to be the result of spaghetti-like flux tubes in the solar wind that are rooted in the Sun and referred to these as filaments. Recently, Borovsky [2006] has revived this concept based on the behavior of spread angle on the scale of 128 s noting that spreads larger than 52° have a different distribution from smaller spreads and could mark out a flux tube structure with an average occurrence rate of 25 min. Burlaga and Ness [1968] found that discontinuities do not clearly outline the boundaries of filaments between which magnetic fields and plasma should vary only slowly. Instead, they concluded that the solar wind is discontinuous rather than occupied by filaments. More recent observations find flux dropouts of energetic ions and suprathermal electrons from the Sun which usually have durations on the order of a few hours [e.g., Larson et al., 1997; Mazur et al., 2000; Gosling et al., 2004a, 2004b]. These do indicate the presence of some flux tube structure in the solar wind but boundaries are relatively far apart. Even if all of these flux tubes had very sharp boundaries, they would not match the occurrence rate of identified discontinuities. Discontinuities with dB/B > 0.2, which are classified as TDs apart from EDs, occur on average every 5 h. This rate is lower than the rate associated with the inferred solar wind flux tube structure. However, if some flux tube boundaries are not sharp or if some are bounded by discontinuities with smaller dB/B, then the observed lower rate can be explained. [59] In the extreme, the number of discontinuities is limited up to the point of filling all space. We estimated that about 3% of the solar wind is filled by discontinuities satisfying our prechosen criteria. Thereby, room for more is available. The average separation between magnetic bright points at the Sun (350 to 700 km) can be mapped to 1 AU using a more than radial expansion factor of 3 to 9 and a distance of 212 solar radii. This corresponds to 2.2 105 1.3 106 km at 1 AU which at a solar wind speed of 400 km/s requires 9 to 54 min to convect past the spacecraft. The identified discontinuities have a separation of several minutes and so potentially could correspond to the magnetic field structure associated with boundaries of magnetic bright points but more likely require a smaller solar structure or substructure within the bright points. [60] The most difficult property to explain consistently with TDs concerns the dV and dB correlation which is generally found in the vicinity of discontinuities [e.g., Belcher and Davis, 1971; Belcher and Solodyna, 1975; Neugebauer et al., 1984; Neugebauer, 1985, 2006]. Once velocity is associated with the discontinuities, one needs to know whether or not the discontinuity is and has been a static boundary across which forces are balanced. Correlated dV and dB fluctuations when associated with open magnetic field regions are more likely to lead to propagating waves and Alfve ́nic turbulence [e.g., Hollweg and Lee, 1989; Parker, 1991]. However, we consider two possibilities below that could give TDs that satisfy the correlation. [61] Neugebauer et al. [1986] considered the potential role of Kelvin-Helmholtz instability at TDs. A more parallel or antiparallel orientation of dV to dB acts to stabilize the instability. Neugebauer theorized that this instability operates at the Sun to remove discontinuities with more perpendicular orientations between dV and dB. [62] Another way to account for the dV and dB correlation is to have Alfve ́nic surface waves supported by the TD [e.g., Hollweg, 1982; Neugebauer, 1985; Horbury et al., 2001; Vasquez et al., 2001; Vasquez, 2005]. Assuming that the discontinuity is purely magnetic, then the velocity seen there is from the wave. If these waves have large amplitudes compared to the magnetic field change across the discontinuity, then what is observed at the discontinuity approaches a case where the observed magnetic field and the velocity appear correlated. However, large amplitude surface waves would cause the cross-product method to give errant normals, which is not found for discontinuities which have triangulated normals. In section 3, the results on crossproduct normals infer that fluctuations in the vicinity of discontinuities on average have relative amplitudes of 5% which is too small to explain dV and dB correlation.
    """
  - """Association With Discontinuities From Alfve ́n Wave Steepening
    The RD can be generated by steepening of an Alfve ́n wave [e.g., Cohen and Kulsrud, 1974; Malara and Elaoufir, 1991; Vasquez and Hollweg, 1996, 1998a, 1998b, 1999a, 1999b, 2001; Medvedev et al., 1997]. The Alfve ́n wave steepens because of the resonance between wave speeds of MHD modes which exists when propagating along the background magnetic field. RDs result when the larger amplitude portion of the wave overruns the smaller amplitude region due to the nonlinear wave magnetic pressure force density r(dB dB)/2m0. The process is halted in a collisionless plasma when ion wave dispersion balances the steepening. This mechanism favors normals which are nearly field aligned. Starting in the corona where waves have small relative amplitudes, nonlinear wave steepening times obtained in the small amplitude and parallel propagating limit from the MHD equations by Cohen and Kulsrud [1974] are approximately 10 h, so that RDs can be generated before transit to 0.2 AU. So RDs should arise during these times, if ever, with large normal magnetic field components. At larger relative amplitudes, the resonance of modes is broadened, and steepening can occur faster and in more oblique directions. The process of RD formation tends to smooth away gradients of B locally in the wave. Time-asymptotically, B shows little change across the discontinuity.
    The RD as a product of Alfve ́n wave evolution is consistent with the observed fluctuation dV and dB correlation in the vicinity of discontinuities. Furthermore, the tendency to small dB/B is partly consistent. However, the intensity change should vanish at long times after steepening, but the discontinuities show a distribution of intensity change. Steepening is expected to produce discontinuities with normals in all directions with a preference for field aligned normals. This is inconsistent with the nearly perpendicular normals found. Steepening would also be expected to proceed from the largest waves, overrunning any smaller discontinuities within the steepening region to produce isolated discontinuities. No more than two per wavelength would be expected. The correlation scale of waves in the solar wind is approximately 106 km. At two per wavelength, the average upper limit on occurrence would be about 2 RDs per hour for average VSW = 381 km/s. Locally, other wavelengths could be associated with the fluctuations, which if shorter than the correlation scale could give a larger upper limit on occurrence rate per hour. Additionally, if the steepening occurs progressively starting and completing at larger amplitudes and longer wavelengths and then proceeding to smaller amplitudes and shorter wavelengths after the larger discontinuities are already produced, then more RDs could be present at 1 AU and large and small ones in close proximity could be observed. Moreover, if fast shocks occur around RDs, then groupings and higher occurrence rates of observed discontinuities might be explained. These fast shocks move away from RD layers just after simulated Alfve ́n waves form imbedded RDs [e.g., Vasquez and Hollweg, 1998b]. However, these fast shocks dissipate at the Landau resonance on the order of 600 proton gyroperiods ( 2 h at 1 AU) and so would not be observed at 1 AU in the solar wind unless the steepening has occurred recently.
    Alternatively, wave steepening may generate kinetic features other than RDs [e.g., Buti et al., 2001]. Tsurutani et al. [2002a, 2002b, 2005a, 2005b, 2007] observe discontinuities with large dB/B that are associated both with Alfve ́nic fluctuations and with magnetic holes and decreases. As discussed in section 1, Tsurutani et al. find that phase steepening and plasma acceleration through a wave ponderomotive force [e.g., Tsurutani et al., 2002b; Dasgupta et al., 2003] can explain the observations. Therefore discontinuities with large dB/B, often associated with static TDs, may in fact be kinetic structures associated with wave steepening or intermediate shocks [Tsurutani et al., 2005a]
    """
  - """Association With Discontinuities From Reconnection
    Reconnection between magnetic fields in different directions can result in the formation of a number of discontinuous features including the RD and slow shock [e.g., Yang and Sonnerup, 1977; Heyn et al., 1988] and can be associated with magnetic holes and decreases [e.g., Farrugia et al., 2000, 2001; Zurbuchen et al., 2001]. The RD which forms always has a small normal field component and so is consistent with this important aspect of the solar wind discontinuities. When formed in a fluid, the RD and slow shock often nearly coincide, so that the discontinuity has properties of a slow shock and is often referred to as a pseudoslow shock. Downstream of the propagation direction of the RD, the magnitude of the velocity transverse to the normal direction increases above that found upstream by the amount of the local Alfve ́n speed. This is the plasma jet associated with the reconnection outflow region. [67] If formed from an impulsive reconnection event, the RD can separate from the slow shock, at least in the fluid description, because they travel at different speeds. In the interplanetary medium, this is an important aspect since the time from formation can be long. Once separated, the RD closely obeys the Walen relation jdVj = jdBj/(m0r)1/2 and shows an increase of the magnitude of the velocity by the amount of the local Alfve ́n speed on its downstream side [e.g., Farrugia et al., 2000, 2001]. Most solar wind reconnection regions are identified by pairs of DDs bounding an outflow region with speeds comparable to the local Alfve ́n speed [e.g., Gosling et al., 2005a, 2005b, 2006a, 2006b, 2006c]. In each pair, the DDs have opposite dV dB correlations with respect to one another which is consistent with ingoing and outgoing propagation, respectively. Here the DDs appear to be RDs only or pseudoslow shocks that do not break up into separate propagating RDs and slow shocks, possibly as a result of driven reconnection and also of ion kinetics which allows the reconnection plasma jet to intermix with the inflow, crossing the contact discontinuity that would exist in the fluid description. Most observed DDs are not ordered in the manner of a reconnection region, do not have associated speed increases, and do not closely satisfy the Walen relation.
    """
  - """Association With Discontinuities From Alfve ́nic Turbulence
    Alfve ́nic MHD turbulence ensues when a large number of Alfve ́n waves travel in many different directions forward and backward with respect to the background magnetic field so that the generalized Reynolds stress r(dV r)dV (dB r)dB/m0 among the waves is nonzero. Analysis and simulations show that fluctuation energy cascades across the background magnetic field to smaller perpendicular scales [e.g., Shebalin et al., 1983; Ng and Bhattacharjee, 1996]. A number of thin current sheets with normals directed across and nearly across the magnetic field develop. In MHD simulations [e.g., Matthaeus et al., 1996; Kinney and MacWilliams, 1998; Cho and Vishniac, 2000; Mu ̈ller and Grappin, 2005], energy dissipates in these sheets due to viscosity and resistivity because of their small scales. The sheets are then transient and are constantly forming and decaying at various positions throughout the simulation box. [69] In our estimation, turbulence gives a convincing explanation for the main properties of observed discontinuities. First, relative intensity changes are mostly small and distributed approximately in accord with a Gaussian distribution suggesting that the changes occur in a random manner. Moreover, Neugebauer [2006] has shown that discontinuities with small intensity changes also have small changes in proton density, alpha concentration, and proton magnetic moment. Small changes in all these quantities are consistent with Alfve ́n waves which are noncompressive wave modes and also with nonlinear interactions among Alfve ́n waves which are nearly incompressible [e.g., Zank and Matthaeus, 1993] or weakly compressive [e.g., Bhattacharjee et al., 1998] in the limit of nearly perpendicular propagation. Second, the dV and dB correlation in the vicinity of discontinuities [e.g., Neugebauer, 2006] is similar to that seen on larger scales associated with Alfve ́nic fluctuations. Third, the high abundance of discontinuities throughout all solar wind sampled is consistent with the nearly ubiquitous presence of Alfve ́nic fluctuations. Since these Alfve ́nic fluctuations have properties consistent with evolving turbulence, we would expect this evolution to result in the formation of current sheets. Fourth, discontinuities have small normal field components as would turbulent-generated current sheets. Fifth, lognormal distributions of separations between discontinuities are consistent with multiplicative random cascades and intermittency which can arise in turbulence (see section 3 for a fuller discussion). Since the discontinuities have a number of properties which are distinct from those in phase-random magnetic fields, they appear to be associated with features generated by the turbulence. [70] Because turbulence is difficult to simulate with current computer resources, a number of details of the evolution of the current sheets are unknown. Most importantly, no simulations including ion kinetics have been done. [71] An outstanding issue concerns whether or not some current sheets persist in plasmas and take on the appearance of TDs but with a dV dB correlation. Instead of dissipating all small scale structure as in fluid simulations, collisionless plasmas can have current sheets which are in equilibrium [e.g., De Keyser and Roth, 1997, 1998]. Persistent sheets from turbulence could evolve if they become close to planar. In this situation, the nonlinear generalized Reynolds stresses nearly vanish because in the limit of one spatial dimension of variation normal to a planar structure, the generalized Reynolds stress is zero if bulk velocity does not change along the normal direction, which is the case for Alfve ́n wave modes. Nonlinearity becomes depleted in the vicinity of the sheet [e.g., Boldyrev, 2005, 2006] and if it does not develop instability within the layer to dissipate its associated energy or current, the sheet will persist. In Knetter’s work, discontinuities are found to be locally planar and may correspond to sheets where nonlinearity is depleted. Thereby, discontinuities may have a close affinity with TDs and yet have the dV-dB correlation associated with an Alfve ́nic feature. Boldyrev [2005, 2006] has theorized that persistent sheets could have important effects on driven perpendicular cascades in that the perpendicular cascade is weakened from a Kolmogorov-like to Kraichnanlike cascade [e.g., Mu ̈ller and Grappin, 2005; Vasquez et al., 2007].
    """
- @madarDirectionalDiscontinuitiesInner2024 "Directional discontinuities in the inner heliosphere from Parker Solar Probe and Solar Orbiter observations"
  - "we observationally confirmed that RDs are produced by Alfvén-wave steepening, while the TDs are most likely the boundaries of flux tubes."
  - "On the other hand, RDs are frequently observed at the edges of or embedded in Alfvén-wave trains, and two of the most popular theories about their formation are turbulent processes and Alfvén-wave steepening (Cohen & Kulsrud 1974; Malara & Elaoufir 1991). The former produce RDs with randomly distributed normals relative to the local magnetic field, while the latter tends to produce discontinuities with typically a large normal component (Vasquez et al. 2007). Thus, it can be decided which of the proposed formation processes is more consistent with the measurements." 
  - "Earlier studies have found that even with the application of the triangulation method, it is not possible to distinguish between a TD and an RD at a heliocentric distance of 1 AU if the RD has small Bn/Bmax parameter (Knetter et al. 2004; Wang et al. 2024). This is mainly due to the low Alfvén velocity at 1 AU, which prevents the triangulation method from detecting whether a DD is propagates relative to the solar wind. We argue that in the vicinity of the Sun, the high propagation velocity of the DDs that are finally classified as RDs is a solid proof of their RD nature. This follows from the requirement that RDs must have a good Walén correlation above the threshold, which (because the Alfvén speed is high near the Sun) also implies a high propagation speed relative to the solar wind. This also means that the uncertainty of the Walén classification decreases closer to the Sun. The clear separation of the two populations shown in Figure 5 strongly suggests that the small Bn/Bmax DDs are mostly TDs everywhere, and thus our new classification scheme, which only uses the magnetic field data, is able to distinguish the two types even for larger solar distances. An important step toward understanding the origin and evolution of the interplanetary discontinuities would be a thorough investigation of their internal structure. Artemyev et al. (2019) demonstrated at a heliocentric distance of 1 AU that the internal structure of DDs is dual, with a thin intense current layer embedded within a thick current sheet for which the Walén relation holds. They stated that this structure endows the discontinuity with both RD and TD-like properties simultaneously, but we argue that these DDs are in fact TDs on which surface Alfvén fluctuations are superposed. This can explain both the jumps in the plasma parameters that (Artemyev et al. 2019) found in the thin current sheets and the RD-like behavior of the outer layer."
  - "The classification also provides the opportunity of investigating the angular distribution of the DD normals in the inner heliosphere. Lukács & Erdo ̋s (2013) found that most of the TDs in the 0.3–1.0 AU region tend to have normals that are normal to the local Parker spiral direction. Liu et al. (2021) reported similar results while investigating the inner heliosphere 0.12–0.80 AU and concluded that RD normals are likely be aligned with the local Parker direction. Using PSP and Solar Orbiter data from 0.06 to 1.01 AU, we repeated the same analysis, but with the correction for the plasma flow direction, which is a combination of the solar wind flow direction and the spacecraft velocity direction. The local Parker spiral direction was determined using a 900 s time window centered on the DDs. These results are shown in Figure 8. It is clear that the RD normals are reasonably well aligned with the Parker direction, but the normals of TDs have a large angle with respect to the local Parker spiral direction. The fact that the two populations show such a distinctly different behavior reconfirms our DD classification. This result agrees with the idea that the majority of TDs are boundaries between flux tubes because the flux tube boundaries are aligned with the Parker spiral on average. It is still debated whether these flux tubes originate from the solar photosphere, as the simplified ‘spaghetti solar wind’ paradigm suggests, or if turbulent mixing creates them. Based on our observation, we cannot rule out any of these possibilities. The RD normals, on the other hand, are mostly well aligned with the local magnetic field, which agrees with the Alfvén-wave steepening mechanism."

### Generation, stability and annihilation

@hoTangentialDiscontinuitiesHigh1995

@tsurutaniInterplanetaryDiscontinuitiesAlfven1995: Abstract. The rate of occurrence of interplanetary discontinuities (ROID) is examined using Ulysses magnetic field and plasma data from 1 to 5 AU radial distance from the Sun and at high heliospheric latitudes. It is found that there are two regions in interplanetary space where the ROID is high: in stream-stream interaction regions and in Alfvén wave trains. This latter feature is particularly obvious at high heliographic latitudes when Ulysses enters a high speed stream associated with a polar coronal hole. These streams are characterized by the presence of continuous, large-amplitude (Δ bar B/l BI - 1 - 2,) Alfvén waves and an extraordinarily high ROID value (∼150 discontinuities/day). In a number of intervals examined, it is found that (rotational) discontinuities are an integral part of the Alfvén wave: they represent ∼ 90° phase rotation of the wave out of the full 360° rotation of the wave. These large amplitude nonlinear Alfvén waves thus appear to be phase steepened. The nonlinear Alfvén waves are spherically polarized, i.e., the tip of the perturbation vector resides on the surface of a sphere (a consequence of constant |B|). The best description of this wave plus discontinuity is a “spherical arc polarization”.

@tsurutaniRapidEvolutionMagnetic2005
They find that in 6 of 6 cases the layer width thinned and in 4 of 6 cases the magnetic decrease clearly deepened between ACE and Cluster. They conclude that these discontinuities undergo rapid changes and can be dissipative [e.g., Lin et al., 1995, 1996; Tsurutani et al., 2002b].

- @vasquezNumerousSmallMagnetic2007
  - "An outstanding issue concerns whether or not some current sheets persist in plasmas and take on the appearance of TDs but with a dV dB correlation. Instead of dissipating all small scale structure as in fluid simulations, collisionless plasmas can have current sheets which are in equilibrium [e.g., De Keyser and Roth, 1997, 1998]. Persistent sheets from turbulence could evolve if they become close to planar. In this situation, the nonlinear generalized Reynolds stresses nearly vanish because in the limit of one spatial dimension of variation normal to a planar structure, the generalized Reynolds stress is zero if bulk velocity does not change along the normal direction, which is the case for Alfve ́n wave modes. Nonlinearity becomes depleted in the vicinity of the sheet [e.g., Boldyrev, 2005, 2006] and if it does not develop instability within the layer to dissipate its associated energy or current, the sheet will persist. In Knetter’s work, discontinuities are found to be locally planar and may correspond to sheets where nonlinearity is depleted. Thereby, discontinuities may have a close affinity with TDs and yet have the dV-dB correlation associated with an Alfve ́nic feature. Boldyrev [2005, 2006] has theorized that persistent sheets could have important effects on driven perpendicular cascades in that the perpendicular cascade is weakened from a Kolmogorov-like to Kraichnanlike cascade [e.g., Mu ̈ller and Grappin, 2005; Vasquez et al., 2007]."

- @sodingRadialLatitudinalDependencies2001
  - "To find a mechanism for the evolution, one should look at the stability of RDs. One-dimensional hybrid simulations do not lead to definite results. While Richter and Scholer (1989) observed that RDs with θBn < 45◦ are unstable, where θBn is the angle between the upstream magnetic field and n, Goodrich and Cargill (1991) observed stable RDs with θBn = 30◦."
