# Quasi-periodic electron precipitation driven by ULF waves: evidence from ELFIN observations.

## Abstract 

Ultra-low frequency (ULF) waves can cause dynamic variations of the electron flux in the equatorial inner magnetosphere. Spacecraft observations have revealed that ULF waves are able to modulate intensity of very-low-frequency (VLF) waves such as whistler waves, whereas resonant scattering of energetic electrons by such modulated whistler waves may further lead to modulated electron precipitation. However, near-equatorial spacecraft measurements cannot resolve the loss cone and hence cannot directly confirm the electron precipitation likely driven by these modulated whistler waves. Understanding the underlying mechanisms and drivers of the electron precipitation in the inner magnetosphere are important for modeling Earth's outer radiation belt dynamics and magnetosphere-ionosphere coupling. In the proposed study, we will use ELFIN low-altitude observations of precipitating electrons to show evidence of quasi-periodic electron precipitation driven by ULF waves. With observations from two ELFIN satellites, we intend to demonstrate that the spatial periodicity of the electron precipitation is likely due to the spatial distribution of the ULF fields in L-shell. The results open new ways to characterize the spatial distribution of ULF waves and the contribution of these waves to precipitation. 

## Background and Motivation

Ultra-low frequency (ULF) waves can be generated by sources external (magnetopause interaction with solar wind transients) or internal (resonant generation by injected energetic ions) to Earth’s magnetosphere and occur in frequencies ranging from 1 mHz to 1 Hz [McPherron, 2005]. ULF waves can interact (resonantly or adiabatically) with both high and low-energy electrons and they can also be coupled with very-low-frequency (VLF) whistler waves in Earth’s magnetosphere [Li et al., 2011; Zhang et al., 2019]. Whistler-mode chorus waves are one of the most intense type of VLF waves in the inner magnetosphere. They have a typical frequency range 0.1-0.8 f_ce (electron cyclotron frequency) [Tsurutani and Smith, 1977]. Previous studies have shown periodic excitation of chorus waves by electron populations modulated by ULF waves across a spatial scale of several Earth radii [e.g., Manninen et al., 2010; Motoba et al., 2015; Xia et al., 2016]. Li et al. [2011] demonstrated that chorus waves can be modulated by compressional Pc4-5 ULF waves exhibiting an anti-correlation between electron density and magnetic field intensity. Zhang et al. [2019] showed that the ULF waves modulate both chorus and electron cyclotron harmonic (ECH) waves over a large spatial scale. They proposed that the periodic excitation of chorus waves is accomplished by ULF modulation of the hot electron drift paths resulting in the perpendicular anisotropy that excites the wave. 
The electron precipitation are attributed mainly to the interaction between electrons and whistler-mode chorus waves near the magnetospheric equator. After chorus waves are generated at the equator, they interact with bouncing electrons in both hemispheres [Kasahara et al., 2018]. Some scattered electrons become nearly aligned with the magnetic field and fill the loss cone. The electrons in the loss cone will then precipitate into the upper atmosphere. Chorus waves play an important role in both electron acceleration and loss. Resonant interaction with lower-band (<0.5 f_ce) chorus waves leads to precipitation of >10s keV electrons [e.g., Li et al., 2009, 2010]. Therefore, ULF waves modulating chorus wave generation could drive energetic (>10 keV) electron precipitation across a large spatial region. The ULF modulated generation of chorus waves does not relate to plasma sheet injections, which is the most traditional source of free energy for wave generation, but represents an alternative free energy source. Thus, it is important to reveal the relative contribution of these modulated whistlers to the resonant electron scattering leading to energetic (>10 keV) electrons precipitation across a large spatial region. Such large-scale precipitation can alter ionospheric properties and reduce the flux of seed electrons available for further acceleration to relativistic energies. For example, the precipitation of energetic electrons owing to whistler-mode wave-particle interactions can cause pulsating aurora [e.g., Sandahl, 1984; Miyoshi et al., 2010]. Therefore, understanding the hot electron precipitation in the inner magnetosphere is important for studying Earth's radiation belt, an important aspect of understanding and predicting space weather. Investigation of electron precipitation requires resolving electron distributions within the loss cone, which is almost impossible near the equator due to the smallness of the loss cone there. However, the much larger loss cone size at low altitudes allows polar-orbiting ionospheric spacecraft to independently measure electron fluxes within the loss cone in-situ, and together with magnetically conjugate equatorial spacecraft and ground-based stations to unravel magnetospheric drivers of electron precipitation such as ULF waves.  In the proposed study, we will use conjugate ground and space observations to reveal evidence of periodic electron precipitation and provide further evidence that it is driven by ULF waves. The primary objective of the proposed research is to present and detail such evidence of the loss process of hot electrons by ULF waves. This will advance our understanding of how electron fluxes vary in the inner magnetosphere and potentially also provide a research tool for studying the ULF waves themselves. 

## Proposed Data and Questions 

### Case studies

We first present two case studies to demonstrate that magnetically conjugate ground and space observations can provide evidence of ULF-driven electron precipitation. The proposed work will refine this evidence and quantify its importance on a case-by-case basis. Future work can expand on this loss mechanism.

Ground-based observations of ULF waves will be obtained from Ground Magnetometer (GMAG) stations from >100 sites worldwide [Russell et al., 2008]. The main advance of ground-based observations is the absence of spatio-temporal ambiguity, which is characteristic of spacecraft measurements. Such ground-based ULF observations will be supplemented by equatorial THEMIS [Angelopoulos, 2008] measurements of ULF and VLF fields. The THEMIS FGM instrument [Auster et al., 2008] measures and stores the magnetic field with a 1/128s, 1/4s or 3s (spin period) sampling rate (depending on data product), whereas the THEMIS SCM instrument [Le Contel et al., 2008] provides < 8kHz wave measurements that are further converted to the FFF spectra data with a frequency resolution of 32 or 64 frequency bands [Cully et al., 2008]. ELFIN’s low-altitude observations are used to analyze the energetic (>50keV) electron precipitation. The pair of identical ELFIN satellites are on a polar, low-Earth orbit and can reveal the specific L-shell (and L-shell range) where ULF-driven precipitation happens. Also, the two ELFIN satellites may pass over the same magnetic longitude with a time separation of 0-60 minutes, and therefore allow disambiguation of the spatial and temporal evolution of electron precipitation [Angelopoulos, Tsai and Bingley et al. 2020]. With two ELFIN satellites, we would then be sure that the periodicity of electron flux precipitation is due to ELFIN crossing different ULF peaks at different L-shells, rather than global temporal variations of the equatorial flux; this can further determine the spatial scale of the electron precipitation.

The first event we use to is on May 13, 2021(Figure 1). 

1. Conjunction (locations)
2. ELFIN observed periodic electron precipitation
3. ULF waves are observed
4. Whistler waves are associated with ULF waves 

Two ground stations (kian and fykn) and three THEMIS satellites all located within the same MLT and L-shell range, observed similar ULF waves with frequency ranging from 3 mHz to 5 mHz. Figures 1f-1h show the wavelet analysis of the parallel component (z component) of the magnetic field in field-aligned coordinates (the magnetic field variation in the other two directions is nearly 0). 

In this case, three THEMIS satellites (TH-A, TH-D, and TH-E) observed ULF waves and quasi-periodic whistler waves, and TH-E's measurements are shown in Figure 1 (h-k). The periodic variation of electron density is shown in Figure 1a, indicating that the observed ULF waves are compressional. Figure 1(b, c) shows the wavelet analysis of the parallel component (z component) of the magnetic field in field-aligned coordinates (the magnetic field variation in the other two directions is nearly 0). The ground station LRV( Leirvogur, Iceland) is close to the ground track of ELFIN’s trajectory. Both the ground station and THEMIS observed the ULF waves with frequency ranging from 2 mHz to 10 mHz. The power of ULF waves  peaks at ~9 mHz and ~3 mHz. Figure 1d shows the magnetic field power spectrum from the SCM instrument. It enables us to identify the periodic whistler waves at a frequency between the low hybrid frequency and half the electron cyclotron frequency. The periodic whistler wave is observed from 05:40 UT to 09:00UT and covers an L shell range from 4-9 (the L shells here are calculated by using the T89 model [Tsyganenko, 1989]). The peaks of whistler wave intensity are correlated with the 8-10 mHz ULF wave (Figure 1e,f,g).

During this event, ELFIN-B is conjugate to THEMIS. The time when ELFIN-B passed over is indicated by the red line in Figure 1. ELFIN-B quickly crossed a large range of L-shells and captured quasi-periodic precipitation of 10s of keV electrons, as shown in Figure 2. ELFIN -B observed six main peaks of precipitation within L=4-9 (Figure 2f). The average distance between major peaks is ~0.8 R_E. It is evident that these periodic peaks contribute to most of the precipitating flux observed during this ELFIN orbit within L=4-8. This indicates that such periodic precipitations can play a major role in energetic electron losses. These precipitations are very likely due to near-equatorial electron scattering by whistler waves driven by compressional ULF waves, because these periodic precipitations are observed within the same L range (L=4-8) as the equatorial ULF/VLF waves. 

The second event (May 14, 2021) is shown in Figures 3 and 4 in a similar format. The two ELFIN satellites are conjugate to the near-equatorial THEMIS satellites and ground-based stations. The THEMIS-E and ELFIN satellites are located within the MLT range 4-7. In this case, ELFIN does not have such a good conjunction with THEMIS but ELFIN A and ELFIN B observed quasi-periodic precipitations. Figure 3 shows wave observations of ULF and whistler waves. The periodic whistler waves are observed at L=6-12. There are two regions of periodic whistler waves. From 20:00 to 20:40 UT, the whistler waves are likely modulated by ~4 mHz ULF waves. From 21:40 to 22:00 UT the whistler waves are likely modulated by ~1.5mHz ULF waves. The time when ELFIN-A passed by is indicated by the blue line in Figure 3. ELFIN-B moves along the same orbit, but with a time lag of ~12 minutes. Both ELFIN-A and ELFIN-B quickly crossed a large range of L-shells and captured quasi-periodic precipitation (J_loss/J_trap) of 10s of keV electrons, as shown in Figure 4. Both ELFIN-A and ELFIN-B observed 5-6 main peaks of precipitation within L=6-12, which indicates that the observed periodicity of precipitation is not due to a temporal effect. The average distances between major peaks of electron precipitations are ~1.1 R_E and ~1.01R_E for ELFIN-A and ELFIN-B respectively.

### Comparing the spatial scales
To further confirm that the periodic electron precipitation is driven by ULF waves, we will compare the spatial scale of periodic precipitation peaks and ULF waves. During these two events, the geomagnetic longitude of the ELFIN satellites is nearly unchanged. Therefore, they measure the quasi-periodic precipitations along an approximately radial direction, when mapped to the equator. The δL between major peaks is ~0.8 R_E and ~1 R_E in event 1 and event 2, respectively (ELFIN time-series of precipitation were transferred to L-shell profiles of precipitation using the T89 magnetic field model). If the precipitation is driven by modulated whistler waves (due to ULF waves), then these δL should be comparable to the ULF wavelength in the radial direction (or, more precisely, the ULF wave periodicity in the radial direction). The wavelength in the radial direction can be calculated by comparing ULF fields measured from two THEMIS satellites separated in the radial direction. If they are radially separated by a distance r and the ULF waves (at frequency f) measured by the two satellites has a phase difference dϕ, then the wavelength can be calculated as λ/2π=r/dϕ. In the first case, THEMIS-A, THEMIS-D, and THEMIS-E are distributed along the radial direction over distances that are comparable with the expected wavelength. We examined the phase difference of 8-10 mHz ULF waves between THEMIS-A and THEMIS-D and found that the estimated wavelength is ~0.7 R_E, which is very close to the δL~0.8R_E. In the second case, the estimated wavelength is also close to the δL observed by ELFIN-A and ELFIN-B. This provides further support for our hypothesis that the periodic precipitation is likely driven by ULF waves. 
In the proposed work, we will investigate further these and other potential candidates of periodic precipitation. Numerous opportunities for dual ELFIN event collections (one-after-another) in close proximity (<10min) exist in the upcoming year (several collected already in the month of January 2022). We expect at least a dozen conjunction events to be available for such studies. Our proposed work will therefore also establish an approximate estimate of how frequently periodic precipitation (likely ULF driven) is observed when the observing conditions are favorable. 
 
### Discussion and future work
In this study, we will focus on the ULF modulated chorus and study how much the modulated whistlers can contribute to the electron precipitation in a large spatial scale. Resonant interaction with whistler waves is not the only cause of electron precipitation.  ULF waves can also directly lead to electron precipitation due to lowering of electrons mirror point [Brito et al., 2012]. However, lowering the mirror altitude by the ULF wave interaction applies to all energies. It is simply due to the ULF compressional component changing the equatorial field and transporting electrons inward or outward. When electrons are transported inward, they are on a shorter field line which lowers the mirror points in order to conserve the second adiabatic invariant. Therefore, electron precipitations caused by ULF waves should not have strong energy dependence. However, in our cases, the strong precipitation peaks mainly appear at lower energies (< 500 keV), which seems consistent with the resonant energy of whistler waves but inconsistent with precipitation driven by ULF waves.  In the future (beyond the present proposal), we may also conduct a more comprehensive statistical analysis of THEMIS/ELFIN comparisons which includes a larger statistical database of events, and further investigation of whether the observed whistler wave characteristics and background magnetic field/plasma conditions are consistent with energies of precipitating electrons (resonant condition) and the intensity of precipitation (diffusion rate estimates).

## Summary 

In this proposal, we will examine and present clear evidence of quasi-periodic electron precipitation driven by ULF waves. We will also examine the potential contribution of ULF driven precipitation for the overall precipitation under similar conditions from a few cases to examine whether such events have the potential to contribute to energetic electron losses. Using conjugate ground-based and space observations, we will show that ULF waves can modulate quasi-periodic whistler-mode chorus waves, such that the modulated chorus waves can result in spatial periodicities of the electron precipitation over a large spatial scale (across the entire auroral zone). The two ELFIN satellites enable us to separate the spatial and temporal effects of electron precipitation. In addition, THEMIS satellites or a ground-based station arrays can be used to compare the L of electron precipitations with the spatial period of ULF waves. Future work can then examine this phenomenon statistically, with more data and more quantitative tests of the wave-particle interactions.  This line of research will help us better understand the electron precipitation process in the Earth’s magnetosphere. 
