sync-overleaf:
   rsync figures/ overleaf/figures/ -r
   rsync proposal_EMIC.tex overleaf/
   rsync proposal_SWD.tex overleaf/
   rsync ~/projects/share/bibliography/ overleaf/files/ -r

default:
   quarto render proposal_EMIC.qmd --to latex -M bibliography:files/references.bib
   mv proposal_EMIC.tex overleaf/